"use strict";
const path = require("path");
const runWebPlatformTest = require("./run-web-platform-test")(exports, path.resolve(__dirname, "tests"));

[
  "dom/nodes/CharacterData-appendData.html",
  "dom/nodes/CharacterData-deleteData.html",
  "dom/nodes/CharacterData-insertData.html",
  "dom/nodes/CharacterData-replaceData.html",
  "dom/nodes/Document-contentType/contentType/createHTMLDocument.html",
  "dom/nodes/Document-createComment.html",
  "dom/nodes/Document-createProcessingInstruction.html",
  "dom/nodes/Document-createProcessingInstruction.xhtml",
  "dom/nodes/Document-createTextNode.html",
  "dom/nodes/Document-implementation.html",
  "dom/nodes/DocumentType-literal.html",
  "dom/nodes/DocumentType-literal.xhtml",
  "dom/nodes/DOMImplementation-createDocumentType.html",
  "dom/nodes/DOMImplementation-createHTMLDocument.html",
  "dom/nodes/DOMImplementation-hasFeature.html",
  "dom/nodes/Element-classlist.html",
  "dom/nodes/Element-getElementsByClassName.html",
  // "dom/nodes/attributes.html", // TODO Attr: once we fix Attr from scratch, this can be enabled
  "dom/nodes/getElementsByClassName-01.htm",
  "dom/nodes/getElementsByClassName-02.htm",
  "dom/nodes/getElementsByClassName-03.htm",
  "dom/nodes/getElementsByClassName-04.htm",
  "dom/nodes/getElementsByClassName-05.htm",
  "dom/nodes/getElementsByClassName-06.htm",
  "dom/nodes/getElementsByClassName-07.htm",
  "dom/nodes/getElementsByClassName-08.htm",
  "dom/nodes/getElementsByClassName-09.htm",
  // "dom/nodes/getElementsByClassName-10.xml", // XML class attribute and localName and namespaces don't work well
  // "dom/nodes/getElementsByClassName-11.xml", // XML class attribute and localName and namespaces don't work well
  "dom/nodes/getElementsByClassName-12.htm",
  "dom/nodes/getElementsByClassName-13.htm",
  "dom/nodes/getElementsByClassName-14.htm",
  "dom/nodes/getElementsByClassName-15.htm",
  "dom/nodes/getElementsByClassName-16.htm",
  "dom/nodes/getElementsByClassName-17.htm",
  "dom/nodes/getElementsByClassName-18.htm",
  "dom/nodes/getElementsByClassName-19.htm",
  "dom/nodes/getElementsByClassName-20.htm",
  "dom/nodes/getElementsByClassName-21.htm",
  "dom/nodes/getElementsByClassName-22.htm",
  "dom/nodes/getElementsByClassName-23.htm",
  "dom/nodes/getElementsByClassName-24.htm",
  "dom/nodes/getElementsByClassName-25.htm",
  "dom/nodes/getElementsByClassName-26.htm",
  "dom/nodes/getElementsByClassName-27.htm",
  "dom/nodes/getElementsByClassName-28.htm",
  "dom/nodes/getElementsByClassName-29.htm",
  "dom/nodes/getElementsByClassName-30.htm",
  "dom/nodes/getElementsByClassName-31.htm",
  "dom/nodes/Node-baseURI.html",
  "dom/nodes/Node-cloneNode.html",
  "dom/traversal/NodeFilter-constants.html",
  "dom/traversal/NodeIterator.html",
  "html/dom/elements/global-attributes/classlist-nonstring.html",
  "html/infrastructure/urls/terminology-0/document-base-url.html",
  "html/syntax/serializing-html-fragments/outerHTML.html",
  "html/semantics/scripting-1/the-template-element/additions-to-the-steps-to-clone-a-node/template-clone-children.html",
  "html/semantics/scripting-1/the-template-element/additions-to-the-steps-to-clone-a-node/templates-copy-document-owner.html",
  "html/semantics/scripting-1/the-template-element/template-element/template-content-node-document.html",
  "html/semantics/scripting-1/the-template-element/template-element/template-content.html",
  "html/semantics/scripting-1/the-template-element/template-element/template-descendant-body.html",
  "html/semantics/scripting-1/the-template-element/template-element/template-descendant-frameset.html",
  "html/semantics/scripting-1/the-template-element/template-element/template-descendant-head.html",
  "html/webappapis/atob/base64.html"
]
.forEach(runWebPlatformTest);
