#!/usr/bin/env node

var nodeunit = require('nodeunit'),
    path = require('path');

var argv = require('./runner-options').argv;

if (argv.help) {
  require('optimist').showHelp();
  process.exit();
}

var fileFilter = [];
var testFilter = [];

Error.stackTraceLimit = 100;

if (argv.suites) {
  fileFilter = argv.suites.replace(/\s/g, '').split(',');
}

if (argv.tests) {
  testFilter = argv.tests.replace(/\s/g, '').split(',');
}

var files = [
  "level1/core.js",
  "level1/html.js",
  "level2/core.js",
  "level2/html.js",
  "level2/style.js",
  "level2/events.js",
  //"level3/core.js",
  //"level3/ls.js",
  "level3/textContent.js",
  "level3/xpath.js",

  "living-dom/attributes.js",
  "living-dom/class-list.js",
  "living-dom/compare-document-position.js",
  "living-dom/dom-implementation.js",
  "living-dom/event-target.js",
  "living-dom/node-clone-node.js",
  "living-dom/node-contains.js",
  "living-dom/node-list.js",
  "living-dom/node-owner-document.js",
  "living-dom/node-parent-element.js",
  "living-dom/query-selector.js",
  "living-dom/query-selector-all.js",
  "living-dom/node-iterator.js",
  "living-dom/parent-node.js",
  "living-dom/non-document-type-child-node.js",
  "living-html/cookie.js",
  "living-html/current-script.js",
  "living-html/focus.js",
  "living-html/htmlanchorelement.js",
  "living-html/htmlbuttonelement.js",
  "living-html/htmlelement.js",
  "living-html/htmlcanvaselement.js",
  "living-html/htmlimageelement.js",
  "living-html/htmlinputelement.js",
  "living-html/htmloptionelement.js",
  "living-html/htmltextareaelement.js",
  "living-html/htmlformelement.js",
  "living-html/inline-event-handlers.js",
  "living-html/location.js",
  "living-html/message-event.js",
  "living-html/navigator.js",
  "living-html/on-error.js",
  "living-html/post-message.js",

  "misc/url.js",
  "misc/xhr-file-urls.js",
  "misc/xhr-requires-server.js",
  "misc/cancel-requests.js",
  "misc/keep-alive-connections.js",

  "window/history.js",
  "window/script.js",
  "window/console.js",
  "window/frame.js",
  "window/base64.js",
  "sizzle/index.js",
  "jsdom/index.js",
  "jsdom/parsing.js",
  "jsdom/env.js",
  "jsdom/utils.js",
  "jsdom/namespaces.js",
  "jsdom/virtual-console.js",
  "jsdom/xml.js",
  "jsdom/selectors.js",
  "jsdom/serialization.js",
  "jsdom/named-properties-tracker.js",
  "jsdom/resource-loading.js",
  "jsdom/reconfigure-window.js",
  "jsdom/node-location.js",
  "living-html/named-properties-window.js",

  "jsonp/jsonp.js",
  "browser/css.js",
  "browser/index.js",
  "web-platform-tests/index.js",
  "web-platform-tests/to-upstream.js",
  "misc/domparsing.js"
];

if (fileFilter.length > 0) {
  files = files.filter(function(val) {
   var ok = false;
   fileFilter.forEach(function(v) {
     if (val.indexOf(v) > -1) {
      ok = true;
     }
   });
   return ok;
  });
}


var modules = {};
var modulesToRun = {};

files.map(function (p) {
  var required = require(path.join(__dirname, p));
  var module = required.tests || required;
  var filteredModule = {};

  if (testFilter.length) {
    var moduleKeys = Object.keys(module);
    testFilter.forEach(function(filter) {
      filter = filter.toLowerCase();
      moduleKeys.forEach(function(moduleKey) {
        if (moduleKey.toLowerCase().indexOf(filter) > -1) {
          filteredModule[moduleKey] = module[moduleKey];
        }
      });
    });
    module = filteredModule;
  }

  if (module && Object.keys(module).length > 0) {
    modulesToRun[p] = module;
  }
});

// Make sure that any Error that occurs in a callback is logged.
// This should not be something we would have to do manually, the test library should handle it...
process.on("uncaughtException", function (err) {
  console.error("Uncaught exception: ", err, err.stack);
  process.exit(1); // Uncaught Fatal Exception
});

var reporter = argv.verbose ? nodeunit.reporters.default : nodeunit.reporters.minimal;
reporter.run(modulesToRun, null, function(err) {
  process.exit(err ? 1 : 0);
});
