[Unforgeable] interface Location {
  stringifier attribute USVString href;
  readonly attribute USVString origin;
           attribute USVString protocol;
           attribute USVString host;
           attribute USVString hostname;
           attribute USVString port;
           attribute USVString pathname;
           attribute USVString search;
           attribute USVString hash;

  void assign(USVString url);
  void replace(USVString url);
  void reload();

//  [SameObject] readonly attribute USVString[] ancestorOrigins;
};
