"use strict";

var w3cTest = require("./w3ctest")(exports);

w3cTest("dom/nodes/CharacterData-appendData.html");
w3cTest("dom/nodes/CharacterData-deleteData.html");
w3cTest("dom/nodes/CharacterData-insertData.html");
w3cTest("dom/nodes/CharacterData-replaceData.html");
w3cTest("dom/nodes/Document-contentType/contentType/createHTMLDocument.html");
w3cTest("dom/nodes/Document-createComment.html");
w3cTest("dom/nodes/Document-createProcessingInstruction.html");
w3cTest("dom/nodes/Document-createProcessingInstruction.xhtml");
w3cTest("dom/nodes/Document-createTextNode.html");
w3cTest("dom/nodes/Document-implementation.html");
w3cTest("dom/nodes/DocumentType-literal.html");
w3cTest("dom/nodes/DocumentType-literal.xhtml");
w3cTest("dom/nodes/DOMImplementation-createDocumentType.html");
w3cTest("dom/nodes/DOMImplementation-createHTMLDocument.html");
w3cTest("dom/nodes/DOMImplementation-hasFeature.html");
w3cTest("dom/nodes/Element-classlist.html");
w3cTest("dom/nodes/Element-getElementsByClassName.html");
w3cTest("dom/nodes/getElementsByClassName-01.htm");
w3cTest("dom/nodes/getElementsByClassName-02.htm");
w3cTest("dom/nodes/getElementsByClassName-03.htm");
w3cTest("dom/nodes/getElementsByClassName-04.htm");
w3cTest("dom/nodes/getElementsByClassName-05.htm");
w3cTest("dom/nodes/getElementsByClassName-06.htm");
w3cTest("dom/nodes/getElementsByClassName-07.htm");
w3cTest("dom/nodes/getElementsByClassName-08.htm");
w3cTest("dom/nodes/getElementsByClassName-09.htm");
//w3cTest("dom/nodes/getElementsByClassName-10.xml"); XML class attribute and localName and namespaces don't work well
//w3cTest("dom/nodes/getElementsByClassName-11.xml"); XML class attribute and localName and namespaces don't work well
w3cTest("dom/nodes/getElementsByClassName-12.htm");
w3cTest("dom/nodes/getElementsByClassName-13.htm");
w3cTest("dom/nodes/getElementsByClassName-14.htm");
w3cTest("dom/nodes/getElementsByClassName-15.htm");
w3cTest("dom/nodes/getElementsByClassName-16.htm");
w3cTest("dom/nodes/getElementsByClassName-17.htm");
w3cTest("dom/nodes/getElementsByClassName-18.htm");
w3cTest("dom/nodes/getElementsByClassName-19.htm");
w3cTest("dom/nodes/getElementsByClassName-20.htm");
w3cTest("dom/nodes/getElementsByClassName-21.htm");
w3cTest("dom/nodes/getElementsByClassName-22.htm");
w3cTest("dom/nodes/getElementsByClassName-23.htm");
w3cTest("dom/nodes/getElementsByClassName-24.htm");
w3cTest("dom/nodes/getElementsByClassName-25.htm");
w3cTest("dom/nodes/getElementsByClassName-26.htm");
w3cTest("dom/nodes/getElementsByClassName-27.htm");
w3cTest("dom/nodes/getElementsByClassName-28.htm");
w3cTest("dom/nodes/getElementsByClassName-29.htm");
w3cTest("dom/nodes/getElementsByClassName-30.htm");
w3cTest("dom/nodes/getElementsByClassName-31.htm");
w3cTest("dom/nodes/Node-baseURI.html");
w3cTest("dom/nodes/Node-cloneNode.html");
w3cTest("dom/traversal/NodeFilter-constants.html");
w3cTest("dom/traversal/NodeIterator.html");
w3cTest("html/dom/elements/global-attributes/classlist-nonstring.html");
w3cTest("html/infrastructure/urls/terminology-0/document-base-url.html");
w3cTest("html/syntax/serializing-html-fragments/outerHTML.html");
w3cTest("html/webappapis/atob/base64.html");

