// https://svgwg.org/svg2-draft/types.html#InterfaceSVGElement
interface SVGElement : Element {

  // Deprecated
  //[SameObject] readonly attribute SVGAnimatedString className;

  //[SameObject] readonly attribute DOMStringMap dataset;

  readonly attribute SVGSVGElement? ownerSVGElement;
  readonly attribute SVGElement? viewportElement;

  //attribute long tabIndex;
  //void focus();
  //void blur();
};

// SVGElement implements GlobalEventHandlers;
// SVGElement implements ElementCSSInlineStyle; // https://drafts.csswg.org/cssom/#the-elementcssinlinestyle-interface